//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Api
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        public int POST_ID { get; set; }
        public string POST_CONTENT { get; set; }
        public Nullable<System.DateTimeOffset> POST_TIME { get; set; }
        public string USER_ID { get; set; }
    }
}
